/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['hapi.js']) {
  _$jscoverage['hapi.js'] = [];
  _$jscoverage['hapi.js'][3] = 0;
}
_$jscoverage['hapi.js'][3]++;
module.exports = {Base64: require("./base64"), Process: require("./process"), Error: require("./error"), Log: require("./log"), Server: require("./server"), Utils: require("./utils")};
_$jscoverage['hapi.js'].source = ["// Export public modules","","module.exports = {","","    Base64: require('./base64'),","    Process: require('./process'),","    Error: require('./error'),","    Log: require('./log'),","    Server: require('./server'),","    Utils: require('./utils')","};",""];
