/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['monitor/base.js']) {
  _$jscoverage['monitor/base.js'] = [];
  _$jscoverage['monitor/base.js'][1] = 0;
  _$jscoverage['monitor/base.js'][3] = 0;
  _$jscoverage['monitor/base.js'][4] = 0;
  _$jscoverage['monitor/base.js'][6] = 0;
  _$jscoverage['monitor/base.js'][7] = 0;
  _$jscoverage['monitor/base.js'][8] = 0;
  _$jscoverage['monitor/base.js'][9] = 0;
  _$jscoverage['monitor/base.js'][12] = 0;
  _$jscoverage['monitor/base.js'][13] = 0;
  _$jscoverage['monitor/base.js'][14] = 0;
  _$jscoverage['monitor/base.js'][18] = 0;
  _$jscoverage['monitor/base.js'][19] = 0;
  _$jscoverage['monitor/base.js'][22] = 0;
  _$jscoverage['monitor/base.js'][26] = 0;
  _$jscoverage['monitor/base.js'][33] = 0;
}
_$jscoverage['monitor/base.js'][1]++;
var Base = {};
_$jscoverage['monitor/base.js'][3]++;
Base.expose = (function (self, obj, keys) {
  _$jscoverage['monitor/base.js'][4]++;
  keys = keys || null;
  _$jscoverage['monitor/base.js'][6]++;
  for (var i in obj) {
    _$jscoverage['monitor/base.js'][7]++;
    if (obj.hasOwnProperty(i)) {
      _$jscoverage['monitor/base.js'][8]++;
      if (keys instanceof Array && keys.indexOf(i) < 0) {
        _$jscoverage['monitor/base.js'][9]++;
        continue;
      }
      _$jscoverage['monitor/base.js'][12]++;
      self.prototype[i] = (function (fn) {
  _$jscoverage['monitor/base.js'][13]++;
  return (function (callback) {
  _$jscoverage['monitor/base.js'][14]++;
  var err = null, result = null;
  _$jscoverage['monitor/base.js'][18]++;
  try {
    _$jscoverage['monitor/base.js'][19]++;
    result = fn();
  }
  catch (err) {
    _$jscoverage['monitor/base.js'][22]++;
    result = null;
  }
  _$jscoverage['monitor/base.js'][26]++;
  callback(err, result);
});
})(obj[i]);
    }
}
});
_$jscoverage['monitor/base.js'][33]++;
module.exports = exports = Base;
_$jscoverage['monitor/base.js'].source = ["var Base = {};","","Base.expose = function(self, obj, keys){","  keys = keys || null;","  ","  for(var i in obj){","    if (obj.hasOwnProperty(i)){","      if (keys instanceof Array &amp;&amp; keys.indexOf(i) &lt; 0){","        continue;","      }","      ","      self.prototype[i] = (function(fn){","        return function(callback){","          var err = null,","              result = null;","          ","          ","          try {","            result = fn();","          } catch (err) {","            // do nothing","            result = null;","            // err = err; // remove or keep? TODO","          }","          ","          callback(err, result);","        };","      })(obj[i]);","    }","  }","};","","module.exports = exports = Base;"];
