/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['monitor/base.js']) {
  _$jscoverage['monitor/base.js'] = [];
  _$jscoverage['monitor/base.js'][1] = 0;
  _$jscoverage['monitor/base.js'][3] = 0;
  _$jscoverage['monitor/base.js'][4] = 0;
  _$jscoverage['monitor/base.js'][6] = 0;
  _$jscoverage['monitor/base.js'][7] = 0;
  _$jscoverage['monitor/base.js'][8] = 0;
  _$jscoverage['monitor/base.js'][9] = 0;
  _$jscoverage['monitor/base.js'][12] = 0;
  _$jscoverage['monitor/base.js'][13] = 0;
  _$jscoverage['monitor/base.js'][14] = 0;
  _$jscoverage['monitor/base.js'][15] = 0;
  _$jscoverage['monitor/base.js'][18] = 0;
  _$jscoverage['monitor/base.js'][21] = 0;
  _$jscoverage['monitor/base.js'][28] = 0;
}
_$jscoverage['monitor/base.js'][1]++;
var Base = {};
_$jscoverage['monitor/base.js'][3]++;
Base.expose = (function (self, obj, keys) {
  _$jscoverage['monitor/base.js'][4]++;
  keys = keys || null;
  _$jscoverage['monitor/base.js'][6]++;
  for (var i in obj) {
    _$jscoverage['monitor/base.js'][7]++;
    if (obj.hasOwnProperty(i)) {
      _$jscoverage['monitor/base.js'][8]++;
      if (keys instanceof Array && keys.indexOf(i) < 0) {
        _$jscoverage['monitor/base.js'][9]++;
        continue;
      }
      _$jscoverage['monitor/base.js'][12]++;
      self.prototype[i] = (function (fn) {
  _$jscoverage['monitor/base.js'][13]++;
  return (function (callback) {
  _$jscoverage['monitor/base.js'][14]++;
  try {
    _$jscoverage['monitor/base.js'][15]++;
    var result = fn();
  }
  catch (err) {
    _$jscoverage['monitor/base.js'][18]++;
    var result = null;
  }
  _$jscoverage['monitor/base.js'][21]++;
  callback(null, result);
});
})(obj[i]);
    }
}
});
_$jscoverage['monitor/base.js'][28]++;
module.exports = exports = Base;
_$jscoverage['monitor/base.js'].source = ["var Base = {}","","Base.expose = function(self, obj, keys){","  keys = keys || null;","  ","  for(var i in obj){","    if (obj.hasOwnProperty(i)){","      if (keys instanceof Array &amp;&amp; keys.indexOf(i) &lt; 0){","        continue;","      }","      ","      self.prototype[i] = (function(fn){","        return function(callback){","          try {","            var result = fn();","          } catch (err) {","            // do nothing","            var result = null;","          }","          ","          callback(null, result);","        };","      })(obj[i]);","    }","  }","}","","module.exports = exports = Base;"];
