name: ci

on:
  push:
    branches:
      - v21
      - master
      - next
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: hapijs/.github/.github/workflows/ci-module.yml@min-node-18-hapi-21
