name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    permissions:
      contents: none
    uses: hapijs/.github/.github/workflows/ci-module.yml@master
